// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjt8XQMj1nkFQTkGLnEsGjHjAfowyWBLk',
    appId: '1:1000085905599:web:e7d1776745c9214e0ca60a',
    messagingSenderId: '1000085905599',
    projectId: 'ytnobs-1d5e5',
    authDomain: 'ytnobs-1d5e5.firebaseapp.com',
    storageBucket: 'ytnobs-1d5e5.appspot.com',
    measurementId: 'G-RDGQ5QM533',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjfxTsf0cP2BN7f_8bWOq6ULKVEiI9loA',
    appId: '1:1000085905599:android:3884033f34bedb7c0ca60a',
    messagingSenderId: '1000085905599',
    projectId: 'ytnobs-1d5e5',
    storageBucket: 'ytnobs-1d5e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN5fHyBTalDN1tVHhM_lBmp9qpokqwQOE',
    appId: '1:1000085905599:ios:6f7a8ab6fb4693ca0ca60a',
    messagingSenderId: '1000085905599',
    projectId: 'ytnobs-1d5e5',
    storageBucket: 'ytnobs-1d5e5.appspot.com',
    iosBundleId: 'com.example.speechContinuousNone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN5fHyBTalDN1tVHhM_lBmp9qpokqwQOE',
    appId: '1:1000085905599:ios:1f7e8cf364f9fd410ca60a',
    messagingSenderId: '1000085905599',
    projectId: 'ytnobs-1d5e5',
    storageBucket: 'ytnobs-1d5e5.appspot.com',
    iosBundleId: 'com.example.speechContinuousNone.RunnerTests',
  );
}
